DROP DATABASE IF EXISTS BBDD_PLAYMOBIL;
CREATE DATABASE BBDD_PLAYMOBIL;

USE BBDD_PLAYMOBIL;

CREATE TABLE USUARIOS (
ID_USER INT (11) AUTO_INCREMENT,
USUARIO VARCHAR (20),
PASSWORD VARCHAR (10),
NOMBRE VARCHAR (30),
DIRECCION VARCHAR (100),
TELEFONO VARCHAR (20),
TIPO_USER VARCHAR (3),
COMPRAS INT (5),
EMAIL VARCHAR (100),
PRIMARY KEY(ID_USER)
 );

CREATE TABLE ARTICULOS (
ID_ART INT (11) AUTO_INCREMENT,
DESCRIPCION VARCHAR (100),
FOTO VARCHAR (50),
PRECIO DOUBLE (11,2),
STOCK INT (11),
PRIMARY KEY(ID_ART)
);

CREATE TABLE CESTA (
ID_CESTA INT (11) AUTO_INCREMENT,
ID_CLIENTE INT (11),
ID_ARTCESTA INT (11),
PRECIO_CESTA DOUBLE (11,2),
UND_CESTA INT (11),
PRIMARY KEY(ID_CESTA)
 );

CREATE TABLE VENTAS (
ID_VENTA INT (11),
ID_LINEA INT (11),
ID_CLIENTE_VT INT (11),
ID_ART_VT INT (11),
FECHA_VT DATE,
PRECIO_ART DOUBLE (11,2),
UND_VENTA INT (11)
 );
